name: PotatoBattles
version: ${project.version}
main: devlaunchers.potatobattles.PotatoBattles
api-version: 1.16
description: The official potato trading card game!!! Collect potatoes and battle them with other players!!!
commands:
  pb:
    description: opens the potato battles ui
    usage: /pb
